### ISSUE TITLE
YTDL_OPTIONS

### ISSUE THREAD

**Issue by rithask** [alexta69/metube#102]
Hello, I've been trying to setup the docker-compose file for MeTube. But I get this error when I try to run the container with english subtitles and chapter marker features enabled. 

docker-compose.yml
```yaml
version: "3"
services:
  metube:
    image: alexta69/metube
    container_name: metube
    restart: unless-stopped
    user: "1001:1001"
    ports:
      - "8081:8081"
    volumes:
      - ./metube-downloads:/downloads
    environment:
      - YTDL_OPTIONS={"writesubtitles": "true", "subtitleslangs": ["en", "-live_chat"], "postprocessors": [{"key": "Exec", "exec_cmd": "chmod 0644", "when": "after_move"}, {"key": "FFmpegEmbedSubtitle", "already_have_subtitle": "false"}, {"key": "FFmpegMetadata", "add_chapters": "true"}]}
```

Error:
`yaml: line 11: did not find expected key`

Any help is appreciated

**Comment by rithask** [comment]
Nevermind. I missed the single quotes. 

For anyone facing the same problem:
```yaml
version: "3"
services:
  metube:
    image: alexta69/metube
    container_name: metube
    restart: unless-stopped
    user: "1001:1001"
    ports:
      - "8081:8081"
    volumes:
      - ./metube-downloads:/downloads
    environment:
      - 'YTDL_OPTIONS={"writesubtitles": "true", "subtitleslangs": ["en", "-live_chat"], "postprocessors": [{"key": "Exec", "exec_cmd": "chmod 0644", "when": "after_move"}, {"key": "FFmpegEmbedSubtitle", "already_have_subtitle": "false"}, {"key": "FFmpegMetadata", "add_chapters": "true"}]}'
```
