### ISSUE TITLE
dont delete file

### ISSUE THREAD

**Issue by Goten87** [alexta69/metube#108]
when i click the trashcan in the webui the file still stays on my local server is there a way then when i press that trashcan on compleeted/failed items it will delete the item also in my folder

also a beter way to download to a other pc is needed now it opens the file in a player i want it to popup a where to save window when you click the name of the download

**Comment by alexta69** [comment]
Regarding the trashcan, I personally prefer it this way, but perhaps there can be an additional icon for removing it from the server.
Regarding downloading the file, you can right-click the link and select "Save link as.." to save it.

**Comment by Goten87** [comment]
Yeah a way to delete from server will be nice 
Well I sayed about the save function becose I have other people using it in house as well who are not realy technical that’s why I wanted it to be more easy

**Comment by xorguy** [comment]
I agree that the trashcan should delete the file from the server, or at least an environmental var to control the behavior.

**Comment by PikuZheng** [comment]
In my environment, I'm more concerned about temporary files (.part/.ytdl) which generated after download failures, or audio/video merge failures. 
Is there a way to delete them automatically, or delete them while click trashcan?

**Comment by alexta69** [comment]
> In my environment, I'm more concerned about temporary files (.part/.ytdl) which generated after download failures, or audio/video merge failures. Is there a way to delete them automatically, or delete them while click trashcan?

MeTube tries to delete the temp files in case of an error. Maybe there are some cases where it doesn't work, MeTube relies on yt-dlp to tell it which temp files exist.. I hope the check is correct. Perhaps it's worth it to review the code and see if anything is being missed.

**Comment by buzzdev** [comment]
> 

to download the file instead of opening it in player, you can add this into nginx config:
`    location ~* ^/.+\.(?:mp4|mp3)$ {
       include /config/nginx/proxy.conf;
       include /config/nginx/resolver.conf;

       add_header Content-disposition "attachment; filename=$1";
       default_type application/octet-stream;

       set $upstream_app metube;
       set $upstream_port 8081;
       set $upstream_proto http;
       proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }`

**Comment by Goten87** [comment]
I don’t think the project uses nginx to host website

**Comment by alexta69** [comment]
Perhaps it will work if you host MeTube behind an NGINX reverse proxy...

**Comment by buzzdev** [comment]
@Goten87 you don't wont to expose this project directly to internet, you'd better use a reverse proxy.
It might be nginx, where the config snippet is from.

I use SWAG for that matter: https://docs.linuxserver.io/general/swag
They even have a ready made proxy conf for metube.

The mimetype is anyway handled by a webserver, however i am not that familiar with the metube internals, but perhaps the correct header could also be set on its internal webserver.

**Comment by Goten87** [comment]
@buzzdev can i use that without a hostname (i want it to be <ip>/metube for example) is this posible or do i need a domein name to use it
also i will not let it go to the outside of my network sins its for internal use only

**Comment by buzzdev** [comment]
@Goten87 i have them under docker-compose and they use the internal service names (if that's what you mean).
The swag has an example config for metube in subdir or subdomain.
https://github.com/linuxserver/reverse-proxy-confs/blob/master/metube.subdomain.conf.sample
https://github.com/linuxserver/reverse-proxy-confs/blob/master/metube.subfolder.conf.sample

I use subdomain in my docker-compose.yml:
```
version: "2.1"
services:
  metube:
    image: ghcr.io/<user>/<image> # i use my own image on ghcr
    container_name: metube
    restart: unless-stopped
    #user: "1000:1000"
    ports:
      - "8081:8081"
    #volumes:
    #  - /your/dir/downloads:/downloads
    environment:
      - OUTPUT_TEMPLATE=%(channel)s-%(id)s.%(ext)s

  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
      - URL=<your_domain>
      - SUBDOMAINS=<your_subdomain>
      - ONLY_SUBDOMAINS=true #optional
      - VALIDATION=http
      - EMAIL=<your@email.com> #optional
      - STAGING=false #optional
      #- CERTPROVIDER= #optional
      #- DNSPLUGIN=cloudflare #optional
      # - DUCKDNSTOKEN=<token> #optional
      #- EXTRA_DOMAINS=<extradomains> #optional
    volumes:
      - /your/dir/swag/config:/config
    ports:
      - 443:443
      - 80:80 # optional
    restart: unless-stopped
```
