### ISSUE TITLE
More quality settings

### ISSUE THREAD

**Issue by auanasgheps** [alexta69/metube#11]
Hi,
Thanks for this great Web GUI for youtube-dl!
The dropdown menu only has options for 1080p, 720p and 480p. Are you planning to add 1440p, 2160p and similar?

**Comment by alexta69** [comment]
Since I don't use these resolutions myself I never bothered to, but I can quickly add them, no problem, which are the popular ones?
(Note that leaving it as Best should download the best version automatically, 2k or 4k or whatever. So you only need to select if you need lower quality.)

**Comment by auanasgheps** [comment]
I guess 1440p and 2160p would make sense. I would not bother with lower than 480p.
Thanks!

**Comment by alexta69** [comment]
2160p is the highest resolution they allow anyway, so it's equivalent with just leaving "Best" selected, no reason to add it in the box. Do you have the need for 1440p specifically?

**Comment by auanasgheps** [comment]
I was playing with different formats and noticed that a video downloaded in 1080p is H264 and 2160p is VP9. I don't know what format uses 1440p but might useful to add it.

**Comment by alexta69** [comment]
I added 1440p, it should appear in the docker image pretty soon.

**Comment by jordanlambrecht** [comment]
@alexta69 How would you feel about adding 2160p?

**Comment by alexta69** [comment]
@jordanlambrecht is there a practical difference between that and "Best"?

**Comment by jordanlambrecht** [comment]
Well, for one, I can't get 4k videos to download with the current UI options- I have to do it via YTDL_OPTIONS env variable:

```yaml
YTDL_OPTIONS: > 
'{"writethumbnail":true,
"writesubtitles": true, 
"subtitleslangs": ["en", "-live_chat"], 
"updatetime": false, 
"postprocessors": [{"key": "Exec", "exec_cmd": "chmod 0664", "when": "after_move"}, {"key": "FFmpegEmbedSubtitle", "already_have_subtitle": false}, {"key": "FFmpegMetadata", "add_chapters": true}], 
"format": "bestvideo[height>=2160]+bestaudio/bestvideo[height<=2160]+bestaudio/best"}'
```

 More so, from a UI/UX perspective it's a lot cleaner and matches the rest of the options.

One would assume that 2160p -> download up to 2160p, 1440p -> download up to 1440p, etc, best -> download the highest quality you can
