### ISSUE TITLE
Docker Image for ARM

### ISSUE THREAD

**Issue by fwidder** [alexta69/metube#12]
Please add a Docker Image for ARM7-Platform.

**Comment by alexta69** [comment]
Hi Florian,
Thanks for the contribution!
At the moment, Docker Hub automated builds are enabled for this project, so every push triggers a build there, and an image is created and retained for distribution by them. I think this is a perfect arrangement and it obviates the need for a CI pipeline here for now. Of course by default only x86_64 images are created. I'd prefer to merge a solution that leaves the build on Docker Hub, but adds images for other platforms, something along the lines of this:
https://github.com/ckulka/docker-multi-arch-example
If you want to push something like that, it'll be more than welcome.
Thanks again!
--Alex

**Comment by fwidder** [comment]
Hey!

Sounds good! I'll take a look at it this weekend and revise the pull request!

Many greetings
Florian

**Comment by LeLunZ** [comment]
Would be really nice to have arm support!

**Comment by fwidder** [comment]
Hey!

Took a little bit longer than planned ... but now it Should work! I Updated the Pull Request (#13 )

Many greetings
Florian

**Comment by alexta69** [comment]
Hey Florian!
That's a whole lot of code right there! Did you take it from somewhere or did you author it for this specific project?
Wrote a couple comments in the PR.
Thanks
Alex

**Comment by fwidder** [comment]
Hey! 

Yeah it's because of the bug mentioned here: https://github.com/ckulka/docker-multi-arch-example#known-limitations

It took the Solution from here: https://github.com/rmoriz/multiarch-test

I also mentioned it in my last Commit-Message.

I will have a look at your Comments on the Code next week and adapt the Code!

Many greetings
Florian

**Comment by xescure** [comment]
Hey!

I know you've specifically stated that you don't want a CI pipeline, but they are just so practical and easy to setup. As far as I know GitHub actions are free for public repos, is there any other reason you would want to leave all the compiling to Docker Hub?

Just out of curiosity I've set it up in a few minutes with this official multiarch [example](https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md) and it works [flawlessly](https://github.com/xescure/metube-multiarch/actions/runs/628076768).

Greetings,
Joseph

**Comment by alexta69** [comment]
Hi @xescure 
It does look very simple! Maybe it's a good idea. So if this is deployed, I'd want to disable the automatic building in Docker Hub, correct?
Do you know if there's any way to sync the README to Docker Hub automatically like it does now, if the automatic builds there are disabled?

Thanks!
Alex

**Comment by xescure** [comment]
Hey,

I did not think of the README issue and I don't think there's a proper way of doing it, but I found this [repo](https://github.com/linuxserver/docker-readme-sync) from linuxserver.io that solves the problem.

I came up with this based on the container, but `bash -c 'node sync'` is not passed properly and I can't figure out why. I'll probably have time later this week to figure it out, but I'd appreciate if someone helped me out before that.
```
jobs:
  dockerhub-sync-readme:
    runs-on: ubuntu-latest
    steps:
      - name: sync readme
        uses: docker://lsiodev/readme-sync:latest
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          GIT_REPOSITORY: xescure/metube-multiarch
          DOCKER_REPOSITORY: xescure/metube-multiarch
          GIT_BRANCH: main
        with:
          args: bash -c 'node sync'
```

Greetings
J
