### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/downloads/.metube'

### ISSUE THREAD

**Issue by korykim** [alexta69/metube#136]
### Solution

- chmod 777 /data/filebrowser/sites/root/Download

- docker-compose.yaml
```yaml
version: "3"
services:
  metube:
    image: alexta69/metube
    container_name: metube
    restart: unless-stopped
    user: "206:1004"
    ports:
      - "8081:8081"
    volumes:
      - /data/filebrowser/sites/root/Download:/downloads
    environment:
      - "YTDL_OPTIONS={\"cookiefile\":\"/downloads/cookies.txt\"}"
```

- docker-compose up -d
-  work done!
