### ISSUE TITLE
Convert subtitles to srt

### ISSUE THREAD

**Issue by olivermonberg** [alexta69/metube#140]
Hi,

Nice web UI.

I am struggling with converting subtitles to srt format. Do you know what I am missing in my docker-compose.yml file?

```
version: "3.8"

metube:
    image: alexta69/metube
    user: 1000:1000
    volumes:
      - ./downloads:/downloads
    environment:
      - YTDL_OPTIONS={"writesubtitles": true, "subtitlesformat": "srt", "postprocessors":[{"key":"FFmpegSubtitlesConvertor","format":"srt"}]} 
```
