### ISSUE TITLE
I can download the video, but I don't know which folder the downloaded video is in

### ISSUE THREAD

**Issue by topmask** [alexta69/metube#162]
The downloaded file could not be found
but
can watch online

docker-compose.yml

```
version: "3"
services:
  metube:
    image: alexta69/metube
    container_name: metube
    restart: unless-stopped
    env_file:
      - config.env
    ports:
      - "8081:8081"
    volumes:
      - /usr/share/MeTube:/downloads

```

config.env
```
UID=www
GID=www
DOWNLOAD_DIR="/var/www"
STATE_DIR="/var/www"
```
