### ISSUE TITLE
Error handling request after updating

### ISSUE THREAD

**Issue by LauraWebdev** [alexta69/metube#186]
Hey there, I'm sure this is not something big, I'm trying to get my docker instance back working and updated to the latest image. Whenever I add a video to the queue, it yields an HTTP500 on the ui and the following error in the logs:

```shell
metube          | INFO:ytdl:adding https://youtu.be/[VIDEOID]: quality='best' format='mp3' already=None folder=None
metube          | ERROR:aiohttp.server:Error handling request
metube          | Traceback (most recent call last):
metube          |   File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
metube          |     resp = await request_handler(request)
metube          |   File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 504, in _handle
metube          |     resp = await handler(request)
metube          |   File "app/main.py", line 87, in add
metube          |     status = await dqueue.add(url, quality, format, folder)
metube          |   File "/app/app/ytdl.py", line 273, in add
metube          |     entry = await asyncio.get_running_loop().run_in_executor(None, self.__extract_info, url)
metube          |   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
metube          |     result = self.fn(*self.args, **self.kwargs)
metube          |   File "/app/app/ytdl.py", line 209, in __extract_info
metube          |     return yt_dlp.YoutubeDL(params={
metube          |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 717, in __init__
metube          |     self.add_post_processor(
metube          |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 798, in add_post_processor
metube          |     assert when in POSTPROCESS_WHEN, f'Invalid when={when}'
metube          | AssertionError: Invalid when=after-move
```

My docker-compose settings are as followed:

```yml
 metube:
    image: alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
        - 'YTDL_OPTIONS={"postprocessors": [{"key": "Exec", "exec_cmd": "chmod 0664", "when": "after_move"}, {"key": "Exec", "exec_cmd": "chown www-data:www-data", "when": "after-move"}]}'
    volumes:
      - /mnt/volume-music:/downloads
```
