### ISSUE TITLE
Password Authentication issue 

### ISSUE THREAD

**Issue by ajnasaboobacker** [alexta69/metube#200]
I was trying to enable password authentication for my metube container so that I could run it behind a reverse proxy.
I attempted to add the environment variable to the compose file as shown below, but it did not work. 

```
environment:
      - YTDL_OPTIONS={"username":"myuser", "password":"mypassword"}

```

here is my compose file just in case.

```
version: "3"
services:
  metube:
    image: alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8031:8081"
    volumes:
      - /mnt/sharedrive/containers/MeTube/downloads:/downloads
    environment:
      - YTDL_OPTIONS={"username":"myuser", "password":"mypassword"}
```
