### ISSUE TITLE
OUTPUT_TEMPLATE doesn't seem to work

### ISSUE THREAD

**Issue by BrightCandle** [alexta69/metube#251]
I am adding the environment variable in a docker_compose file as the following but instead of the title.ext I am seeing a random ID with no extension. I was trying to see if I could update the file naming but it appears setting the output template even to the default breaks the naming.

- OUTPUT_TEMPLATE="%(title)s.%(ext)s"

A glance at how the config gets loaded and how the template is used in the download has left me none the wiser as to how I should format this or what I have done wrong or if there is a bug.

**Comment by PikuZheng** [comment]
Some websites do not provide title, please try YouTube to see if it is normal

**Comment by BrightCandle** [comment]
This is what I am using that causes me issues.

```
version: "2.2"
services:  
  metube:
    image: alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ${STORAGE}/Youtube:/downloads
    environment:
      - UID=${PUID}
      - GID=${PGID}
      - STATE_DIR=${STORAGE}/metube/
      - OUTPUT_TEMPLATE="%(title)s.%(ext)s"
      - YTDL_OPTIONS={"updatetime":false}
```

**Comment by PikuZheng** [comment]
this works for me:
```
version: "2.2"
services:  
  metube:
    image: alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ${STORAGE}/Youtube:/downloads
    environment:
      - UID=${PUID}
      - GID=${PGID}
      - STATE_DIR=${STORAGE}/metube/
      - OUTPUT_TEMPLATE=%(title)s.%(ext)s
      - YTDL_OPTIONS={"updatetime":false}
```

**Comment by om555** [comment]
I have the same issue with the following docker-compose file.
```
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    environment:
      - UID=${PUID}
      - GID=${PGID}
      - TZ=${TZ}
      - STATE_DIR=.
      - OUTPUT_TEMPLATE=%(playlist&{}/|)s%(playlist_index&{} - |)s%(title)s.%(ext)s
    volumes:
      - ${MEDIA_ROOT}/youtube:/downloads
    ports:
      - 4848:8081
```
When I tried with yt-dlp directly, the output file was what I expected.
`yt-dlp.exe -s --print filename -o "%(playlist&{}/|)s%(playlist_index&{} - |)s%(title)s.%(ext)s" <youtube_playlist_url>`
