### ISSUE TITLE
YouTube: downloaded files as mp3, completed files linked as webm in UI

### ISSUE THREAD

**Issue by kosikond** [alexta69/metube#252]
When I download YouTube links as best mp3 audio, files are downloaded+processed correctly, but UI links them as `.webm`

Source: `https://www.youtube.com/watch?v=LvKho_C5YwI`, suffix YOUTUBE
File on disk: 
```
$ docker exec -it metube2 sh
ls -lha /downloads
total 438M
drwxr-xr-x 3 1000 1000 4.0K Apr 20 20:07 .
drwxr-xr-x 1 root root 4.0K Apr 20 19:16 ..
drwxr-xr-x 2 1000 1000 4.0K Apr 20 19:16 .metube
-rw-r--r-- 1 1000 1000 272M Apr 20 19:59 MIXCLOUD.Vertigo_B2B_Woice_@_Dark_Days_w_L33_Spot_Club_Liberec_24.03.2023.mp3
-rw-r--r-- 1 1000 1000 2.4M Nov 12 17:32 SOUNDCLOUD.Sub_Focus_-_Off_The_Ground_Laminar_Bootleg.mp3
-rw-r--r-- 1 1000 1000 165M Apr  2 18:34 YOUTUBE.Rene_Lavice_-_Beats_for_Love_2022_Drum_and_Bass.mp3
```
File linked in UI: `https://metube-nginx-test.kosikond.net/download/YOUTUBE.Rene_Lavice_-_Beats_for_Love_2022_Drum_and_Bass.webm`

![Screenshot 2023-04-20 at 21 05 14](https://user-images.githubusercontent.com/1444670/233476092-d7dd6497-5bfb-4431-8bff-009eb81bb5ea.png)

Attaching docker-compose.yml below. I am able to replicate same behaviour with Caddy as reverse proxy. Browser independent issue. No errors yt-dlp DEBUG log file.

```
version: "3"
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube2
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - downloads:/downloads
    environment:
      umask: 000
      PID: 1000
      GID: 1000
      DOWNLOAD_DIRS_INDEXABLE: true
      DOWNLOAD_DIR: '/downloads'
      AUDIO_DOWNLOAD_DIR: '/downloads'
      OUTPUT_TEMPLATE: '%(title)s.%(ext)s'
      YTDL_OPTIONS: '{"restrictfilenames": true, "verbose": true}'
    networks:
      - edge

networks:
  edge:
    external: true
    name: edge

volumes:
  downloads: {}
```

Other content providers like Soundcloud or Mixcloud work fine, files are linked with correct filetype suffix (see in ls output above). Could this issue be caused by commit in #239 ?

Thank you

**Comment by alexta69** [comment]
Could be caused by that commit. :( Can you check with a version before that commit?
Not sure how to make everybody happy here.

**Comment by kosikond** [comment]
Revert got it working. I pulled fresh image, then reverted inside container in `/app/app/ytdl.py` the changed line in 26112c3 , so it's `['filepath']` in dict on line 74

```
/app # cat app/ytdl.py | grep filepath

self.status_queue.put({'status': 'finished', 'filename': d['info_dict']['filepath']})
```

Source URL: `https://www.youtube.com/watch?v=deTJ513J07Y` (audio only / best / mp3)
Env variables in docker-compose.yml:
```
    environment:
      #umask: 000
      #PID: 1000
      #GID: 1000
      DOWNLOAD_DIRS_INDEXABLE: true
      #DOWNLOAD_DIR: '/downloads'
      #AUDIO_DOWNLOAD_DIR: '/downloads'
      OUTPUT_TEMPLATE: '%(title)s.%(ext)s'
      YTDL_OPTIONS: '{"restrictfilenames": true, "verbose": true}'
```

Final download URL : `https://metube-nginx-test.kosikond.net/audio_download/Sub_Focus_-_Fine_Day_Visualiser.mp3`

![Screenshot 2023-04-25 at 11 54 52](https://user-images.githubusercontent.com/1444670/234256012-d82315d2-f183-4767-aa55-bea3c8794ebd.png)
