### ISSUE TITLE
Unable to reverse proxy successfully

### ISSUE THREAD

**Issue by topmask** [alexta69/metube#270]
configuration

docker-compose.yml

```
version: "3"
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "127.0.0.1:9696:9696"
    volumes:
      - /downloads/youtube:/downloads
    environment:
      UID: 106
      GID: 112


```
sudo docker ps -a

```
4b6d3b3c5d50   ghcr.io/alexta69/metube     "./docker-entrypoint…"   2 hours ago    Up 2 hours              8081/tcp, 127.0.0.1:9696->9696/tcp   metube

```

nginx 

```
location /metube/ {
#        proxy_pass http://localhost:9696;
        proxy_pass http://127.0.0.1:9696;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade"; 
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_read_timeout      600s;
        proxy_send_timeout      600s;
}

}

```

Can't open the page
