### ISSUE TITLE
Issue with File Deletion in Metube Deployment

### ISSUE THREAD

**Issue by JaninaK2000** [alexta69/metube#285]
Hello,

I'm currently encountering a challenge with my metube deployment. Specifically, I'm unable to delete files, despite configuring "DELETE_FILE_ON_TRASHCAN" to true and not using the subfolder option. The issue persists in that the files don't get deleted from the disk and also remain visible on the website.

Interestingly, I had no problem deleting files a few days ago. In an attempt to troubleshoot, I've verified the file ownership and access rights, both of which are in order. There's also ample disk space, so it doesn't seem to be a storage issue.

Earlier today, I removed the entire content of the metube download folder, which included all videos and audio files, as well as the .metube folder. After this, I redeployed the Docker container by fetching the source again, using Portainer. Regrettably, this hasn't resolved the problem. After downloading a new YouTube file, I still couldn't delete it.

Would anyone be able to provide some insight or solutions for this issue?

My YAML file for your reference:

```
version: "3"
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    ports:
      - "5000:8081"
    volumes:
      - /home/KJ/docker/mt/dl:/downloads
    environment:
      DELETE_FILE_ON_TRASHCAN: true
```
