### ISSUE TITLE
Help with Youtube-dlp

### ISSUE THREAD

**Issue by tarunkumar519** [alexta69/metube#296]
I cannot make this compose work no matter how much i tweak YTDL_OPTIONS. What is going wrong ? I want to download only first 3 vids on the playlist

```
version: "3"
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - /portainer/Files:/downloads
    environment:
      - YTDL_OPTIONS={"playlist-items":"1:3"}
```
