### ISSUE TITLE
queue not loaded after docker container restart

### ISSUE THREAD

**Issue by swoop124** [alexta69/metube#315]
hello,

i am using metube an it is working well. But when i have to restart the container the queue is not loaded:
This is a Log from start of container.

```
metube  | Setting umask to 022
metube  | Creating download directory (/downloads), state directory (/downloads/.metube), and temp dir (/downloads)
metube  | Changing ownership of download and state directories to 1000:1000
metube  | Running MeTube as user 1000:1000
metube  | INFO:main:Listening on 0.0.0.0:8081
metube  | DEBUG:asyncio:Using selector: EpollSelector
metube  | INFO:ytdl:waiting for item to download
metube  | ERROR:asyncio:Task exception was never retrieved
metube  | future: <Task finished name='Task-3' coro=<DownloadQueue.__import_queue() done, defined at /app/app/ytdl.py:205> exception=AttributeError("'DownloadInfo' object has no attribute 'custom_name_prefix'")>
metube  | Traceback (most recent call last):
metube  |   File "/app/app/ytdl.py", line 207, in __import_queue
metube  |     await self.add(v.url, v.quality, v.format, v.folder, v.custom_name_prefix)
metube  | AttributeError: 'DownloadInfo' object has no attribute 'custom_name_prefix'
metube  | Invalid session mH6NLJ1soj5qOLeWAAAS (further occurrences of this error will be logged with level INFO)
metube  | ERROR:engineio.server:Invalid session mH6NLJ1soj5qOLeWAAAS (further occurrences of this error will be logged with level INFO)
```

This is my docker-compose.yml

```
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=xxxx
      - xxxxxx
      - xxxxxx
    ports:
      - "8081:8081"
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./appdata:/gluetun

metube:
    image: alexta69/metube
    container_name: metube
    restart: unless-stopped
    network_mode: "service:gluetun"
#    ports:
#      - "8081:8081"
    volumes:
      - /opt/downloads:/downloads
```

i have updated metube a view days ago. so no update available
When i use metube normaly then it is working fine, but if i have to restart the container no downloads are visible.

How can i load the queue so the other downloads that are to be downloaded can start?
