### ISSUE TITLE
Swag/Authelia Breaks Browser Extension - Which path to bypass?

### ISSUE THREAD

**Issue by Tyree** [alexta69/metube#318]
Wanting to use Swag/Authelia to add some protection to the reverse-proxied address for MeTube.
I'm finding it breaks browser extensions. Is there a path that extensions use that I can bypass in Authelia? For example, /api. so that https://metube.domain.com asks for auth, but https://metube.domain.com/api doesn't.

Thanks!

**Comment by jhaendel** [comment]
When using Authelia it's possible to define a bypass rule for certain host, method or resource combinations, like so:

```yaml
access_control:
  rules:
  - domain: metube.domain.com
    policy: bypass
    methods:
    - POST
    resources:
    - '^/add$'
```

 See [official documentation here](https://www.authelia.com/configuration/security/access-control/#resources) for details.
