### ISSUE TITLE
TEMP_DIR also in /downloads

### ISSUE THREAD

**Issue by DavidHenryThoreau** [alexta69/metube#330]
I've set `docker-compose.yml` : 

```
version: "3"
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - DELETE_FILE_ON_TRASHCAN=true
      - TEMP_DIR=/tmp/metube-temp
      - STATE_DIR=/tmp/
      - OUTPUT_TEMPLATE=%(playlist)s/%(title)s.%(ext)s
      - 'YTDL_OPTIONS={"add-metadata":true}'
    volumes:
      - /data/metube-dl:/downloads
    ports:
      - 8081:8081
    restart: unless-stopped

```
`TEMP_DIR` is set to `/tmp/metube-temp` but it also written to `/downloads` but I would like metube moves files to `/downloads` when download is finished not during downloading.

**Comment by PikuZheng** [comment]
have you tried to set TEMP_DIR to /tmp ?

**Comment by DavidHenryThoreau** [comment]
Yes, and also change `AUDIO_DOWNLOAD_DIR` same issue :

```
version: "3" 
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - DELETE_FILE_ON_TRASHCAN=true
      - TEMP_DIR=/tmp
      - AUDIO_DOWNLOAD_DIR=/mnt
      - STATE_DIR=/tmp
      - OUTPUT_TEMPLATE=%(playlist)s/%(title)s.%(ext)s
      - 'YTDL_OPTIONS={"add-metadata":true}'
    volumes:
      - /data/metube-dl/dl:/downloads
      - /data/metube-dl/audio:/mnt
    ports:
      - 8081:8081
    restart: unless-stopped
```
