### ISSUE TITLE
How to run on a local USB drive

### ISSUE THREAD

**Issue by gregory-chatelier** [alexta69/metube#381]
My main SSD became defective after too much use. I decided to mount a volume on an external HDD via USB (under Windows), with extended privileges (I don't care about local security). Here's how :

```
version: "3"
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    privileged: true
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    volumes:
      - D:/metube/downloads:/downloads
```
