### ISSUE TITLE
Mkv Format To Download

### ISSUE THREAD

**Issue by PitchAbyss** [alexta69/metube#403]
hi Dev Can you please add mkv format please

![image](https://github.com/alexta69/metube/assets/13099434/909d0b36-6db8-4ab7-8375-9dbf7478bd24)

**Comment by PikuZheng** [comment]
set YTDL_OPTIONS = {'merge_output_format': 'mkv'} ？

**Comment by PitchAbyss** [comment]
> set YTDL_OPTIONS = {'merge_output_format': 'mkv'} ？

How and where to add this sir

**Comment by Doomnometron** [comment]
> set YTDL_OPTIONS = {'merge_output_format': 'mkv'} ？

Doesn't work for me. I've added the option in different spellings as environment variables in the Docker container but the videos are not downloaded in mkv format. I was also unsuccessful with 'remux-video mkv'.

**Comment by PikuZheng** [comment]
sorry to hear that :(
but mkv format will never be downloaded by yt-dlp, all formats are converted by ffmpeg after downloading.

**Comment by Doomnometron** [comment]
Thanks, I'll have a look at it later. I was just looking at the file extension.

**Comment by PitchAbyss** [comment]
> Thanks, I'll have a look at it later. I was just looking at the file extension.

Thankyou it would be great if there is a fix

**Comment by jakejackson** [comment]
@PitchAbyss & @Doomnometron :

Here's my docker-compose for MeTube-- all videos are processed into MKV containers, and I have all audio-only downloads going into M4A containers:

```yaml
version: "3"
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8083:8081"
    volumes:
      - /mnt/metube:/downloads
    network_mode: bridge
    ulimits:
        nofile:
            soft: 200  # Soft limit for open file descriptors
            hard: 400  # Hard limit for open file descriptors
    environment:
      YTDL_OPTIONS: '{"format": "bestvideo+bestaudio", "merge_output_format": "mkv", "writesubtitles": true, "subtitleslangs": ["en"], "postprocessors": [{"key": "FFmpegEmbedSubtitle", "already_have_subtitle": false}, {"key": "FFmpegMetadata", "add_chapters": true}], "outtmpl": "/downloads/%(title)s.%(ext)s", "cachedir": false}'
      YTDL_AUDIO_ONLY_OPTIONS: '{"format": "bestaudio", "merge_output_format": "m4a", "outtmpl": "/downloads/%(title)s.%(ext)s"}'
    labels:
      - com.centurylinklabs.watchtower.enable=true
```

There are obviously a number of other options / audio only options that have been customized to how I want things downloaded and post-processed, but the above will hopefully put you on the path to making it work for your requirements.
