### ISSUE TITLE
Plex friendly like ytdl-sub

### ISSUE THREAD

**Issue by prologic** [alexta69/metube#414]
I tried this out today, and it looks promising. What I need it to do though, and I'm not yet sure how to do this, but it looks like it might? Is make this Plex friendly like ytdl-sub. ytdl-sub creates a structure like this:

```
./Friendly Jordies
./Friendly Jordies/fanart.jpg
./Friendly Jordies/poster.jpg
./Friendly Jordies/Season 2024
./Friendly Jordies/Season 2024/s2024.e020101 - statement from friendlyjordies.info.json
./Friendly Jordies/Season 2024/s2024.e020101 - statement from friendlyjordies.mp4
./Friendly Jordies/Season 2024/s2024.e020101 - statement from friendlyjordies-thumb.jpg
./Friendly Jordies/.ytdl-sub-Friendly Jordies-download-archive.json
```

Which Plex happily picks up using its normal "TV Show" agent. The `.json` file tracks Youtube Video ID(s) so videos already present are not downloaded again.

**Comment by PikuZheng** [comment]
are you means download-archive like #328

**Comment by prologic** [comment]
I _think_ `- 'YTDL_OPTIONS={"download_archive":"archive_downloads.txt","updatetime":false,"postprocessors":[{"key":"Exec","exec_cmd":"chmod 0664","when":"after_move"},{"key":"FFmpegMetadata","add_chapters":true}]}' ` is only half the equation. I need to create the same structure that the Plex TV Show scanner/agent understand hmmm

**Comment by prologic** [comment]
For example I'm not actually sure (yet) how `ytdl-sub` creates `Season 2024/s2024.e020101` <-- this part of the structure...

**Comment by prologic** [comment]
Just playing around with yt-dlp directly and this is _sooo_ close:

```
$ yt-dlp -c -i -v -f "bv+ba/b" --write-thumbnail --convert-thumbnails png --embed-thumbnail --embed-metadata --embed-info-json --download-archive ./Youtube/archive.txt -i -o "./Youtube/%(uploader)s/Season %(upload_date>%Y)s/s%(upload_date>%Y)s.e%(upload_date>%m%d)s01 - %(title)s.%(ext)s" 'https://youtu.be/AADUUz2xqos'
```

All I'm missing is the channel's poster art. Is there an option for this?

And how do I configure metube to use such a complex array of options?

**Comment by prologic** [comment]
Success! (_partially_) 🥳 I have set these enviornment variables:

```
DOWNLOAD_DIR=/youtube
OUTPUT_TEMPLATE=%(uploader)s/Season %(upload_date>%Y)s/s%(upload_date>%Y)s.e%(upload_date>%m%d)s01 - %(title)s.%(ext)s
YTDL_OPTIONS={"format":"bv+ba/b","format_sort":["codec:avc:m4a"],"writeinfojson":true,"writethumbnail":true,"download_archive":"/youtube/archive.txt"}
```

Full Docker Compose YAML:

```yaml
---

version: "3.8"

services:
  metube:
    image: ghcr.io/alexta69/metube:latest
    environment:
      - DOWNLOAD_DIR=/youtube
      - OUTPUT_TEMPLATE=%(uploader)s/Season %(upload_date>%Y)s/s%(upload_date>%Y)s.e%(upload_date>%m%d)s01 - %(title)s.%(ext)s
      - 'YTDL_OPTIONS={"format":"bv+ba/b","format_sort":["codec:avc:m4a"],"writeinfojson":true,"writethumbnail":true,"download_archive":"/youtube/archive.txt"}'
    volumes:
      - youtube:/youtube

volumes:
  youtube: {}
```
