### ISSUE TITLE
WebSocket fails when running behind Authelia & Caddy

### ISSUE THREAD

**Issue by danshat** [alexta69/metube#459]
Apparently after (relatively) recent updates Metube fails to work correctly while running behind Authelia and a reverse proxy.

This is how the page looks, showing "Connection to server" message.

![](https://github.com/alexta69/metube/assets/13084473/e3a3eeb7-7f9b-42b8-95c3-cb6e824c425c)

Network tab shows the following. 

![](https://github.com/alexta69/metube/assets/13084473/4002e059-a9eb-4469-9bbc-0e416a1b4fab)

docker-compose.yml:

```
 metube:
        container_name: metube
        image: alexta69/metube:latest
        volumes:
            - *******:/downloads
        restart: unless-stopped

```

Authelia logs show this repeatedly:

```
time="2024-06-21T00:07:51Z" level=info msg="Access to https://metube.example.com/socket.io/?EIO=4&transport=polling&t=P0u7k_t (method GET) is not authorized to user <anonymous>, responding with status code 302 with location redirect to https://auth.example.com/?rd=https%3A%2F%2Fmetube.example.com%2Fsocket.io%2F%3FEIO%3D4%26transport%3Dpolling%26t%3DP0u7k_t&rm=GET" method=GET path=/api/authz/forward-auth remote_ip=192.168.0.1
```

Caddyfile configuration:

```
metube.example.com {
        forward_auth authelia:9091 {
                uri /api/authz/forward-auth
                copy_headers Remote-User Remote-Groups Remote-Name Remote-Email
        }
        reverse_proxy metube:8081
}
```

I understand this is likely an issue with misconfigured Caddy instance. However if someone could possibly help me with this it would be great.
