### ISSUE TITLE
Document how to load plugins into MeTube

### ISSUE THREAD

**Issue by msfjarvis** [alexta69/metube#461]
yt-dlp's upstream policies sometimes prevent extractors from being upstreamed to their repo in which case it is quite helpful to use their plugin system to add them. While it is [well documented](https://github.com/yt-dlp/yt-dlp#installing-plugins) how to install plugins for use with the yt-dlp CLI, it is somewhat less obvious how to do it for MeTube.

It'd be great to have some documentation around this, if it's even possible at all.

**Comment by p0358** [comment]
The proper way would be to derive the Dockerfile and add it there, plus install pip packages that it needs.

But I'm too lazy for that, so I'll present a ghetto method. Note that this wouldn't be needed if it wasn't for deps being needed.

1. Clone to local dir
```bash
git clone https://github.com/Schmoaaaaah/yt-dlp-stash.git ./yt-dlp-stash
```
2. Install packages
```bash
docker run --rm -it -v $(pwd)/yt-dlp-stash:/yt-dlp-stash python:alpine /bin/ash
cd /yt-dlp-stash
mkdir junk
apk add --no-cache --virtual .build-deps gcc musl-dev
pip install -r requirements.txt -t junk
exit
```
3. In docker compose:
```yaml
    volumes:
      - ./yt-dlp-stash:/etc/yt-dlp-plugins/yt-dlp-stash
    environment:
      - 'PYTHONPATH=/etc/yt-dlp-plugins/yt-dlp-stash/junk'
      - 'YTDL_OPTIONS={"postprocessors":[{"key":"Stash","when":"after_video","scheme":"http","host":"stash","port":9999,"apikey":""}]}'
```
