### ISSUE TITLE
Support MergerFS in docker container

### ISSUE THREAD

**Issue by ChrisWeiss** [alexta69/metube#486]
There are two closed issues that revolve around permissions issues when running metube in a container pointing to a MergerFS volume (add myself to the list of blocked users):
https://github.com/alexta69/metube/issues/174
https://github.com/alexta69/metube/issues/121

It would be helpful to either solve the permissions issue, or (at the very least, instructions on how to) include MergerFS components in the Dockerfile.

**Comment by PikuZheng** [comment]
Alpine Linux support mergerfs on edge branch only. so maybe you want build your image with [this](https://github.com/PikuZheng/metube/blob/PikuZheng-patch-1/Dockerfile.alpine)
(not tested)

**Comment by Betonhaus** [comment]
I must misunderstand how docker paths work, wouldn't the host os handle the mergerfs pool so that the docker container  linked to a directory in it only sees it as a simple directory and the host handles the rest? I have been able to successfully run metube and download using it when the download directory is on my mergerfs pool
```
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
#      - 8086:8081
    volumes:
      - /mnt/work/metube:/tmp
      - /mnt/pool/import/metube:/downloads
      - /mnt/docker/metube/cookies:/cookies
      - /mnt/docker/metube:/config
    environment:
      - UID=1000
      - GID=1002
      - UMASK=002
      - TZ=redacted
      - URL_PREFIX=/metube
      - DEFAULT_THEME=dark
      - DELETE_FILE_ON_TRASHCAN=true
      - TEMP_DIR=/tmp
      - STATE_DIR=/config
      - YTDL_OPTIONS={"cookiefile":"/cookies/cookies.txt"}
    networks:
      - dockerbridge
```
`/mnt/dsk/*/ /mnt/pool fuse.mergerfs defaults,nonempty,allow_other,use_ino,cache.files=partial,moveonenospc=true,dropcacheonclose=true,minfreespace=10G,category.create=mspmfs,fsname=mergerfs 0 0`
