### ISSUE TITLE
Regression on OUTPUT_TEMPLATE

### ISSUE THREAD

**Issue by aegershman** [alexta69/metube#497]
I'm using `OUTPUT_TEMPLATE` to save videos with the "uploader" name automatically create a parent folder. Using `latest` or the latest pinned, `2024-08-19`, the value of OUTPUT_TEMPLATE is ignored and all videos are stored under a folder that gets created titled `NA`. Note I'm working directly with videos, not playlists.

Current trimmed docker-compose:

```yml
services:
  metube:
    image: ghcr.io/alexta69/metube:2024-08-19
    # image: ghcr.io/alexta69/metube:2024-08-02
    environment:
      - OUTPUT_TEMPLATE=%(uploader)s/%(title)s [%(id)s].%(ext)s
```

This appears to be a regression because if you change the image tag back to an earlier tag, for example `2024-08-02`, the results work fine, and videos are saved as expected.

For example, using this youtube video: https://www.youtube.com/watch?v=7EuKibmlll4

On latest / 2024-08-19:

<img width="1059" alt="Screenshot 2024-08-20 at 10 08 56 PM" src="https://github.com/user-attachments/assets/60660e4f-4829-4f4c-8d81-e812a3dacc52">

On 2024-08-02:

<img width="1031" alt="Screenshot 2024-08-20 at 10 12 08 PM" src="https://github.com/user-attachments/assets/ff76f2c3-258a-4ff5-9457-bf9dfc0e5a3d">

**Comment by PikuZheng** [comment]
yt-dlp nightly build maybe works.

**Comment by labmonkey** [comment]
This was introduced by the new `OUTPUT_TEMPLATE_PLAYLIST` in last update. I will fix this.

**Comment by aegershman** [comment]
Tested, all's good. Thank you!

**Comment by loomweaver** [comment]
I am still experiencing this issue on `latest` (`2024-08-22`), not for individual videos, but when attempting to scrape a channel. 

Trimmed docker-compose:
```
version: "3"
services:
  metube:
    image: ghcr.io/alexta69/metube
    environment:
      - 'AUDIO_DOWNLOAD_DIR=/audio-downloads'
      - 'CUSTOM_DIRS=false'
      - 'CREATE_CUSTOM_DIRS=false'
      - 'YTDL_OPTIONS={"writesubtitles":true,"subtitleslangs":["en","-live_chat"], "subtitlesformat":"ass", "download_archive":"/downloads/download_archive.txt"}'
      - 'OUTPUT_TEMPLATE=%(webpage_url_domain)S/%(channel)S (%(channel_id)S)/(%(timestamp>%Y-%m-%d-%H-%M-%S)S) %(title)S (%(height)sp-%(id)S).%(ext)s'
```

For example, downloading https://www.youtube.com/channel/UCBa659QWEk1AI4Tg--mrJ2A/videos places the folder into `/downloads/Tom Scott - Videos` rather than adhering to `OUTPUT_TEMPLATE` formatting.
