### ISSUE TITLE
YTDL_OPTIONS is invalid

### ISSUE THREAD

**Issue by biberino** [alexta69/metube#50]
My docker-compose.yml:

```
version: "3"
services:
  metube:
    image: alexta69/metube
    container_name: metube
    restart: unless-stopped
    environment:
      - URL_PREFIX=/metube/
      - YTDL_OPTIONS={"audio_format":mp3}
    user: "1001:1001"
    ports:
      - "8081:8081"
    volumes:
      - /opt/metube/downloads:/downloads
```

Gives me the error: 
```
metube    | YTDL_OPTIONS is invalid
```

It works without the YTDL_OPTIONS env variable.
