### ISSUE TITLE
Error on starting Docker container on Debian 

### ISSUE THREAD

**Issue by Hoempi** [alexta69/metube#510]
I'm trying to spin up a new instance of metube, as I'm changing my hardware. On the old system I was using Portainer, on the new one I'm using Dockge.

My compose.yaml:
```
version: "3"
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: dok013-metube
    restart: unless-stopped
    ports:
      - 10813:8081
    volumes:
      - /var/docker-data/metube/downloads:/downloads
    environment:
      - UID=1001
      - GID=100
      - TZ=Europe/Berlin
      - URL_PREFIX=https://metube.hempen.family
networks: {}
```
When trying to start the container I get the following output:

> dok013-metube  | Running MeTube as user 1001:100
> dok013-metube  | Traceback (most recent call last):
> dok013-metube  |   File "/app/app/main.py", line 233, in <module>
> dok013-metube  |     raise e
> dok013-metube  |   File "/app/app/main.py", line 229, in <module>
> dok013-metube  |     app.add_routes(routes)
> dok013-metube  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 373, in add_routes
> dok013-metube  |     return self.router.add_routes(routes)
> dok013-metube  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> dok013-metube  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_urldispatcher.py", line 1214, in add_routes
> dok013-metube  |     registered_routes.extend(route_def.register(self))
> dok013-metube  |                              ^^^^^^^^^^^^^^^^^^^^^^^^
> dok013-metube  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_routedef.py", line 76, in register
> dok013-metube  |     return [reg(self.path, self.handler, **self.kwargs)]
> dok013-metube  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> dok013-metube  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_urldispatcher.py", line 1180, in add_post
> dok013-metube  |     return self.add_route(hdrs.METH_POST, path, handler, **kwargs)
> dok013-metube  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> dok013-metube  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_urldispatcher.py", line 1114, in add_route
> dok013-metube  |     resource = self.add_resource(path, name=name)
> dok013-metube  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> dok013-metube  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_urldispatcher.py", line 1091, in add_resource
> dok013-metube  |     raise ValueError("path should be started with / or be empty")
> dok013-metube  | ValueError: path should be started with / or be empty

Any ideas which path could be wrong?
