### ISSUE TITLE
Apache server reverse proxy

### ISSUE THREAD

**Issue by mihha** [alexta69/metube#52]
Hi,

could it be possible to include also Apache server reverse proxy configuration example?

Thank you in advance!

Regards,
Igor

**Comment by alexta69** [comment]
Hi Igor,
I'm not an Apache user myself, so I don't have such a configuration. However if someone is willing to contribute it, I'll gladly add it to the README for everyone else to benefit.
Alex

**Comment by mihha** [comment]
Can you tell me what is the websocket port which you are using in MeTube?

**Comment by alexta69** [comment]
Port 8081, the same one used for the rest of the HTTP communication.

**Comment by parampavar** [comment]
Here is my service definition used in docker-compose.
The UI comes up fine, but the download does not start after adding a playlist.
You may have better luck
NOTE: The reverse proxy that I use is traefik
```
  metube:
    image: alexta69/metube
    container_name: metube
    networks:
      - t2_proxy
      - socket_proxy
    restart: "no"
    user: "$PUID:$PGID"
    ports:
      - "8082:8081"
    environment:
      # - DOWNLOAD_DIR='/downloads/'
      # - AUDIO_DOWNLOAD_DIR=
      - OUTPUT_TEMPLATE="[%(album)s][%(artist)s][%(title)s].%(ext)s"
      - YTDL_OPTIONS={"sleep_interval":10}
    volumes:
      # - /path/to/downloads:/downloads
      - $DATASTORE_DOWNLOADDIR/audio:/downloads
    # depends_on: [traefik, nocodb-db]
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.metube.entrypoints=https"
      - "traefik.http.routers.metube.rule=Host(`metube.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.metube.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.metube-rtr.service=metube-svc"
      - "traefik.http.services.metube-svc.loadbalancer.server.port=8081"
```
