### ISSUE TITLE
Audio file not handled correctly in the WebUI if you send them to another AUDIO_DOWNLOAD_DIR

### ISSUE THREAD

**Issue by BaguaXingyiZhang** [alexta69/metube#533]
I have an issue, that I can change the `AUDIO_DOWNLOAD_DIR` and it will comply to it, but the link in the WebUI won't change to the right URL, it just stays with `/download/file` even if you change `PUBLIC_HOST_AUDIO_URL` accordantly.

For example I download one video from YouTube with the option **any** if will download it. In the complete list it will be at `http://server:8081/download/file.webm`. If I download the same video again and choose the **flac** format afterwards, it will download and overwrite the pervious entry to `http://server:8081/download/file.flac`. So the old entry isn't anymore in the list and the new entry of the music file is in the wrong directory.

I still can access both files fine over the index with `DOWNLOAD_DIRS_INDEXABLE`, but the WebUI mess it up.

Also if you let both types in the same directory the `*.webm` will be deleted after creating the `*.flac`.

Here is my `docker-compose.yml`. Ich also tried to set `PUBLIC_HOST_AUDIO_URL` to `http://server:8081/audio_download` before, but nothing seems to effect the link to the content.

```
services:
  metube:
    image: 'ghcr.io/alexta69/metube'
    container_name: 'metube'
    restart: 'unless-stopped'
    environment:
      AUDIO_DOWNLOAD_DIR: /downloads/audio_download
      CREATE_CUSTOM_DIRS: true
      CUSTOM_DIRS: true
      DEFAULT_OPTION_PLAYLIST_ITEM_LIMIT: 0
      DEFAULT_OPTION_PLAYLIST_STRICT_MODE: false
      DEFAULT_THEME: dark
      DELETE_FILE_ON_TRASHCAN: false
      DOWNLOAD_DIR: /downloads/download
      DOWNLOAD_DIRS_INDEXABLE: true
      GID: 1000
      HTTPS: false
      OUTPUT_TEMPLATE: %(title)s.%(ext)s
      OUTPUT_TEMPLATE_CHAPTER: %(title)s - %(section_number)s %(section_title)s.%(ext)s
      OUTPUT_TEMPLATE_PLAYLIST: %(playlist_title)s/%(title)s.%(ext)s
#      PUBLIC_HOST_URL: 
      PUBLIC_HOST_AUDIO_URL: audio_download/
      STATE_DIR: /downloads/state/.metube
      TEMP_DIR: /downloads/tmp
      UID: 1000
      UMASK: 027
      URL_PREFIX: /
networks:
      metube: {}
    ports:
      - '8081:8081'
    volumes:
      - '/data/metube/downloads:/downloads'

networks:
  metube:
    driver: 'bridge'
```
