### ISSUE TITLE
ERROR: [youtube] : No video formats found!

### ISSUE THREAD

**Issue by ivoarch** [alexta69/metube#537]
Hi, I get this error every time I try to download video from Youtube .

My docker-compose.yml

```
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - "/mnt/pve/sb/downloads:/downloads:rw"
```

Is my first install and setup,

What I missing ?
Thanks!
