### ISSUE TITLE
[Support] Attempting to make a options file but container will always error out with `YTDL_OPTIONS_FILE contents is invalid`

### ISSUE THREAD

**Issue by binder-badge** [alexta69/metube#658]
I need help with making a options file for metube. I assume ive done something wrong to make Metube complain what I assume to be an syntax error somewhere.  It doesnt help that the error doesnt say anything else about what is wrong with the file, so im not sure why it errors out. I want my options file to embed metadata and thumbnails, and ive used the `cli_to_api.py` script to make the API options. 

below is the env vars for my docker compose for metube: 
```yaml
    environment:
      - DELETE_FILE_ON_TRASHCAN=true
      - YTDL_OPTIONS_FILE=/options.json
    volumes:
      - ./downloads:/downloads
      - ./cookies.firefox-private.txt:/cookies.txt:ro
      - ./ytdl_options.json:/options.json:ro
```

Here is the contents of my config file:
```json
{
  "outtmpl": {"pl_thumbnail": ""},
  "postprocessors": [{"add_chapters": true, "add_infojson": "if_exists", "add_metadata": true, "key": "FFmpegMetadata"},
                     {"already_have_thumbnail": False, "key": "EmbedThumbnail"}],
   "writethumbnail": true
}
```
